platform :ios, '8.0'
use_frameworks!

inhibit_all_warnings!

target 'DKImagePickerControllerDemo' do

  pod 'DKImagePickerController', :path => '../'

  # Pods for DKImagePickerControllerDemo

  target 'DKImagePickerControllerDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
